# Generated by Django 2.0.5 on 2018-05-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=20, unique=True)),
                ('uPass', models.CharField(default=None, max_length=20)),
                ('uIP', models.CharField(max_length=20)),
                ('uComName', models.CharField(max_length=20)),
            ],
        ),
    ]
