# Generated by Django 2.0.5 on 2018-05-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='userTable',
        ),
    ]
