# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0003_auto_20180525_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='cPosition',
            new_name='cVoteType',
        ),
    ]
