# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 11:59
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0004_auto_20180525_1754'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='candidate',
            managers=[
                ('cmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
