# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0007_auto_20180525_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cImgName',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='crType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='VoteApp.VoteType'),
        ),
    ]
