# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0009_auto_20180526_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uDate', models.DateField(auto_now=True)),
                ('uNameId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='VoteApp.User')),
                ('uWhoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='VoteApp.Candidate')),
            ],
            options={
                'db_table': 'userVoteRecord',
            },
        ),
    ]
