# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0010_uservoterecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoterecord',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
