# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-27 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0012_remove_user_ucomname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecord',
            name='crName',
            field=models.CharField(max_length=20),
        ),
    ]
