# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0013_auto_20180527_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoterecord',
            name='uRemark',
            field=models.FloatField(default=0),
        ),
    ]
