# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0015_auto_20180528_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoterecord',
            name='uType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='VoteApp.VoteType'),
        ),
    ]
