# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0016_uservoterecord_utype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cDeclaration',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cImgName',
            field=models.CharField(default='who.jpg', max_length=20),
        ),
    ]
