# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0017_auto_20180528_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cDeclaration',
            field=models.CharField(default='', max_length=300),
        ),
    ]
