# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0019_uservoterecord_ctimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoterecord',
            name='cTimes',
            field=models.IntegerField(default=1),
        ),
    ]
