# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0020_auto_20180528_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservoterecord',
            old_name='cTimes',
            new_name='uTimes',
        ),
    ]
