# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0023_auto_20180528_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cDeclaration',
            field=models.CharField(default='我那么美，给高点分呗', max_length=300),
        ),
    ]
