# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0024_auto_20180528_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uNickName',
            field=models.CharField(default='guest', max_length=20),
        ),
    ]
