# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteApp', '0025_user_unickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecord',
            name='crNickName',
            field=models.CharField(default='guest', max_length=20),
        ),
    ]
